x-global: &global
  restart: unless-stopped

services:
  mire:
    <<: *global
    # image: mire
    build:
      context: .
      dockerfile: Dockerfile.mire
    container_name: mire
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"

  nginx_proxy:
    <<: *global
    # image: openresty/openresty:1.21.4.1-0-alpine
    # image: openresty_luaprom
    build:
      context: .
      dockerfile: Dockerfile.openresty
    container_name: nginx_proxy
    volumes:
      - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx_cache:/etc/nginx/nginx_cache:rw
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080
      - NGINX_PROXY=mire
      - NGINX_PROXY_PORT=3000
    depends_on:
      - mire

  prometheus:
    <<: *global
    image: prom/prometheus
    user: root
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus:rw
    ports:
      - "9090:9090"
    depends_on:
      - nginx_proxy

  nginx_exporter:
    <<: *global
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx_proxy
    command:
      - -nginx.scrape-uri=http://nginx_proxy:8080/stub_status

  grafana:
    <<: *global
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - 3100:3000
    env_file:
      - .env