FROM node:22.6.0-bullseye-slim AS build
WORKDIR /app
COPY mire/package*.json ./
COPY mire/ .
RUN npm ci && npm run build

FROM node:22.6.0-bullseye-slim AS stage
WORKDIR /app
COPY mire/package*.json ./
COPY --from=build /app/build ./build
RUN npm ci --omit=dev && npm cache clean --force
EXPOSE 3000
CMD ["node" , "build/server.js"]