scrape_configs:
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
    # nginx-exporter
      - targets: ['nginx_exporter:9113']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    # prometheus
      - targets: ['localhost:9090']