{
 "title": "Nginx Lua",
 "description": "Nginx dashboard for nginx-lua-prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "instance",
    "query": "label_values(nginx_http_connections, instance)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nginx_http_request_duration_seconds_bucket{instance=\"$server\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS proxy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{job=\"nginx_lua\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{job=\"nginx_lua\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total{instance=\"$server\", host!~\"|127.0.0.1\"}[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nginx HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_http_connections{instance=\"$server\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Request Duration Percentile - $host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.999, rate(nginx_http_request_duration_seconds_bucket{instance=\"$server\", host=\"$host\"}[1m]))",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Requests by Status - $host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"$server\", host=\"$host\"}[2m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}